added __main__.py, changed get_issues.py. #2
gotohe11/get_issues pull request #1
Opened 2024-02-28 14:55 UTC by gotohe11

bla-bla

2024-02-29 13:47 UTC, gotohe11 commented on __main__.py
> +
ololo pysh pysh

2024-02-29 14:01 UTC, protoss-player commented on get_issues.py
> +    """A function that returns a list of open issues (not pull-request)
```suggestion
    """ Returns the list of open issues (not pull-request)
```

Не нужно писать, что это function, оно и так понятно.

2024-02-29 14:05 UTC, protoss-player commented on __main__.py
> +project_name = input('input GitHub repo ID in format owner/repo (for example, "s0md3v/Photon"):')
Тут лучше -- хоть это и `__main__.py` -- тоже убрать код под `if __name__ == '__main__'`.

Во-первых, для единообразия.
Во-вторых, это настолько распространённый паттерн на питоне, что я бы сразу пошёл искать `__main__`.

Точнее, стоит сделать так:

```python
def main():
    # код

if __name__ == '__main__':
    main()
```

2024-02-29 14:23 UTC, protoss-player commented on get_issues.py
> +        return ("OOPS! Something went wrong. "
Тут лучше выкинуть исключение, иначе как код, который вызывает эту функцию, должен отличать успех от ошибки?

2024-02-29 14:36 UTC, protoss-player commented on get_issues.py
>      response = requests.get(base_url)
Всё ещё +1 запрос остаётся. Результат это запросы ты по сути выкидываешь - от него только `status` используется, хотя он честно возвращает первую страницу исусов.

2024-02-29 14:37 UTC, protoss-player commented on get_issues.py
>          for item in response.json():
Тут нет проверки на ошибку в ответе, подозрительно.

2024-02-29 14:38 UTC, protoss-player requested changes
Посмотрел. Все места, где нужны правки, отметил.

Всё ещё остаётся лишний запрос к API, от него бы избавиться.

2024-02-29 16:53 UTC, gotohe11 commented on get_issues.py
>          for item in response.json():
а надо проверять status_code на каждой странице репозитория?

2024-02-29 18:13 UTC, protoss-player commented on get_issues.py
>          for item in response.json():
По идее, надо, иначе могут рандомные исключения тут выпрыгивать, типа `incorrect json` или ещё что-то такое.

Вообще при работе со сторонними ресурсами не стоит полагаться на то, что у них всё гарантированно работает.

2024-03-01 13:34 UTC, protoss-player commented on get_issues.py
> +                if 'pull_request' not in item.keys():
Вот это, кстати, не понял. Чем так уж криминально наличие ссылки на PR в исусе? Оно по сути означает, что для бага кто-то предложил фикс, который болтается на ревью.

2024-03-01 13:36 UTC, protoss-player commented on get_issues.py
> +def get_issues_list(project_name):
Неплохо бы обработать ошибки и для них выбрасывать внятные исключения. Как минимум, если на вход подать не существующий проект, сейчас произойдёт что-то мутное. Стоит подумать, какие ещё ситуации лучше явно обработать.

2024-03-01 13:52 UTC, gotohe11 commented on get_issues.py
> +def get_issues_list(project_name):
Если дать несуществующий проект, то эта функция выдаст пустой список issue_list, соответственно, далее total_list тоже будет пустой. А еще далее печатающая функция принимает пустой список и печатает сообщение об ошибке (правда, вариант, что если просто у репозитория реально нет исусов, не продуман). 
Меня больше интересует вопрос, что делать и как определить, если вдруг на 5 из 10 страниц произошла ошибка по невиданным причинам.

2024-03-01 13:57 UTC, gotohe11 commented on get_issues.py
> +                if 'pull_request' not in item.keys():
GitHub по API выдает вперемешку исусы и ПР. Условно, если открыть страницу какого то репозитория, то на вкладке исусов можно увидеть их 14 штук, а запросив по API получишь 24 и не будет понятно, где что.
Ты изначально просил исусы, я их отделила (инфа про смешанные исусы и ПР есть на самом гитхабе)

2024-03-11 09:58 UTC, protoss-player commented on cli.py
> +        global project_name
А это зачем?

2024-03-11 09:59 UTC, protoss-player commented on cli.py
> +        global pretty_issues_list
И это зачем? Не догоняю, для чего тут `global`

2024-03-11 10:01 UTC, protoss-player commented on cli.py
> +        global pretty_issues_list
Ааа, понел, никогда так не пользовался global'ом, даже и не знал, что можно.

Обычно глобальные переменные - это плохо, лучше бы без них.

2024-03-11 10:02 UTC, protoss-player commented on cli.py
> +                               issues_list[i][1][0:10],
Что за вуду мэджик?

2024-03-11 10:04 UTC, protoss-player commented on cli.py
> +        for i in range(len(issues_list)):
Для такого в питоне есть встроенная функция `enumerate`, с ней перебор списков удобнее делать.

Будет что-то в духе:

```
for i, issue in enumerate(issues_list):
    pretty_issues_list.append((i + 1, issue[0], issue[1][0:10], ...))
```

2024-03-11 10:04 UTC, protoss-player commented on cli.py
> +            pretty_issues_list.append((i + 1,
Сомнительное форматирование кода, лучше все отступы сделать одинаковыми.

2024-03-11 10:06 UTC, protoss-player commented on cli.py
> +            issues_num = int(command[command.index('(') + 1: command.index(')')])
Эт чё за колдунство?

2024-03-11 11:31 UTC, gotohe11 commented on cli.py
> +                               issues_list[i][1][0:10],
в изначальном виде формат вывода данных с гитхаба - не очень "красивый": там и буквы и точное время - ненужная инфа для юзера. я сделала список более читабельным таким образом

2024-03-11 11:33 UTC, gotohe11 commented on cli.py
> +        for i in range(len(issues_list)):
что такое припоминаю, гляну еще раз

2024-03-11 11:41 UTC, protoss-player commented on cli.py
> +                               issues_list[i][1][0:10],
Охотно верю, но это никак не помогает понять, что же там ожидается в `[1]` и в `[0:10]`.

Если магия неизбежна, стоит хотя бы протаскивать её через промежуточные внятные шаги. Например, можно было бы сделать так:

```
current_issue = issues_list[i]
title = current_issue[0]
date = current_issues[1][0:10]
...
pretty_issues_list.append((i + 1, title, date, ...))
```

Так общий смысл гораздо проще уловить.

2024-03-11 11:43 UTC, protoss-player commented on cli.py
> +                               issues_list[i][1][0:10],
Либо можно было вообще не перепаковывать исусы из словарей, а оставить их, как есть. Тут бы просто `issue['title']` получилось, не нужно было б гадать.

2024-03-12 11:20 UTC, gotohe11 commented on cli.py
> +                               issues_list[i][1][0:10],
В процессе борьбы с магией решила добавлять сразу из словаря нужную инфу. Норм?
![Снимок экрана 2024-03-12 141814](https://github.com/gotohe11/get_issues/assets/158286178/1a2795e2-47d3-4c44-97d4-7f6157682762)

2024-03-12 11:26 UTC, protoss-player commented on cli.py
> +                               issues_list[i][1][0:10],
Так гораздо лучше. Только остались мистические `[0:10]`. Их бы либо на что-то explicit заменить (типа, распарсить дату, напечатать нужные компоненты), либо хотя бы коммент подписать о том, чё ожидается от этих `0:10`.

2024-03-12 20:55 UTC, protoss-player commented on cli.py
> +        if len(user_command.lower().split()) > 1:
Смысл проверки не выкупил.

Можно же всегда сделать что-то в духе:

```
parts = user_command.split()
cmd = parts[0]
if len(parts) > 1:
    args = parts[1:]
else:
    args = []
```

2024-03-12 20:57 UTC, protoss-player commented on cli.py
> +            issue_number = int(user_command[1])
А зачем нам тут знать семантику аргументов? Мы ж только командную строку парсим, кроме её формата особо ничё и не знаем.

Функции-хендлеры команд могут сами определять смысловую нагрузку аргументов.

2024-03-12 21:31 UTC, protoss-player commented on cli.py
> +command_dict = {
Куда команда `/get` пропала? Надо бы заменить нынешний ввод имени проекта на неё.

2024-03-12 21:31 UTC, protoss-player approved these changes
В целом пока сойдёт. Думаю, можно смержить этот PR, чтобы следующие правки проще было разбирать.

2024-03-13 10:34 UTC, gotohe11 commented on cli.py
> +        if len(user_command.lower().split()) > 1:
я сделала примерно то же самое, только более рукожопски :-)

2024-03-13 10:48 UTC, merged